### ISSUE TITLE
Error compiling Cython file

### ISSUE THREAD

**Issue by habedi** [libnano/primer3-py#13]
Hi, I get this error when I'm trying to install primer3-py,
```bash
[BLAH BLAH BLAH ...]
gcc -g -Wall -D__USE_FIXED_PROTOTYPES__ -O2 -I klib -o long_seq_tm_test long_seq_tm_test_main.c oligotm.o  -lm
Compiling primer3/thermoanalysis.pyx because it changed.
Cythonizing primer3/thermoanalysis.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        int align_end_1
        int align_end_2



    void thal(  const unsigned char*,
                              ^
------------------------------------------------------------

primer3/thermoanalysis.pxd:57:31: Expected ')', found 'char'

Error compiling Cython file:
------------------------------------------------------------
...
    ctypedef enum salt_correction_type:
        schildkraut    = 0
        santalucia     = 1
        owczarzy       = 2

    double seqtm(const char*,
                          ^
------------------------------------------------------------

primer3/thermoanalysis.pyx:58:27: Expected ')', found '*'
Traceback (most recent call last):
  File "setup.py", line 180, in <module>
    force=True
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 517, in cythonize
    cythonize_one(pyx_file, c_file, quiet, options)
  File "/usr/lib/pymodules/python2.7/Cython/Build/Dependencies.py", line 540, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: primer3/thermoanalysis.pyx
```

Any particular reason? and thanks in advance.

**Comment by benpruitt** [comment]
It looks like your version of Cython may be out of date. Can you try updating it to the latest version (with pip/homebrew or whatever you prefer) and then re-trying the primer3-py install?

**Comment by habedi** [comment]
You're right, I've just reached the same conclusion a minutes ago. 
btw thank you for the answer.
